apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openfaas
    chart: openfaas-4.4.0
    component: nats
    heritage: Tiller
    release: openfaas
  name: nats
  selfLink: /api/v1/namespaces/openfaas/services/nats
spec:
  ports:
  - name: clients
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
