apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: dask
    chart: dask-2.2.1
    component: worker
    heritage: Tiller
    release: intent-penguin
  name: intent-penguin-dask-worker
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/intent-penguin-dask-worker
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: worker
      release: intent-penguin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask
        component: worker
        release: intent-penguin
    spec:
      containers:
      - args:
        - dask-worker
        - intent-penguin-dask-scheduler:8786
        - --no-bokeh
        image: daskdev/dask:1.1.0
        imagePullPolicy: IfNotPresent
        name: intent-penguin-dask-worker
        ports:
        - containerPort: 8789
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
