apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: dask
    chart: dask-2.2.1
    component: scheduler
    heritage: Tiller
    release: intent-penguin
  name: intent-penguin-dask-scheduler
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/intent-penguin-dask-scheduler
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: scheduler
      release: intent-penguin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask
        component: scheduler
        release: intent-penguin
    spec:
      containers:
      - args:
        - dask-scheduler
        - --port
        - "8786"
        - --bokeh-port
        - "8787"
        image: daskdev/dask:1.1.0
        imagePullPolicy: IfNotPresent
        name: intent-penguin-dask-scheduler
        ports:
        - containerPort: 8786
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
