apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: dask
    chart: dask-2.2.1
    component: jupyter
    heritage: Tiller
    release: intent-penguin
  name: intent-penguin-dask-jupyter
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/intent-penguin-dask-jupyter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: jupyter
      release: intent-penguin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask
        component: jupyter
        release: intent-penguin
    spec:
      containers:
      - env:
        - name: DASK_SCHEDULER_ADDRESS
          value: intent-penguin-dask-scheduler:8786
        image: daskdev/dask-notebook:1.1.0
        imagePullPolicy: IfNotPresent
        name: intent-penguin-dask-jupyter
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/jovyan/.jupyter
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: intent-penguin-dask-jupyter-config
        name: config-volume
status: {}
