apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dask
    chart: dask-2.2.1
    component: jupyter
    heritage: Tiller
    release: intent-penguin
  name: intent-penguin-dask-jupyter
  selfLink: /api/v1/namespaces/default/services/intent-penguin-dask-jupyter
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30659
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: dask
    component: jupyter
    release: intent-penguin
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
