apiVersion: v1
data:
  master.conf: |-
    dir /data
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
  redis.conf: |-
    # User-supplied configuration:
    # maxmemory-policy volatile-lru
  replica.conf: |-
    dir /data
    slave-read-only yes
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: redis
    chart: redis-7.0.0
    heritage: Tiller
    release: airflow
  name: airflow-redis
  selfLink: /api/v1/namespaces/airflow/configmaps/airflow-redis
