apiVersion: v1
data:
  git-clone.sh: |
    #!/bin/sh -e
    REPO=$1
    REF=$2
    DIR=$3
    # Init Containers will re-run on Pod restart. Remove the directory's contents
    # and reprovision when this happens.
    if [ -d "$DIR" ]; then
        rm -rf $( find $DIR -mindepth 1 )
    fi
    git clone $REPO $DIR
    cd $DIR
    git reset --hard $REF
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: airflow
    chart: airflow-3.0.5
    heritage: Tiller
    release: airflow
  name: airflow-git-clone
  selfLink: /api/v1/namespaces/airflow/configmaps/airflow-git-clone
