apiVersion: v1
data:
  install-requirements.sh: |
    #!/bin/sh -e
    if [ ! -d /usr/local/airflow/dags ]; then
      echo "No folder /usr/local/airflow/dags"
      exit 0
    fi
    cd /usr/local/airflow/dags
    if [ -f requirements.txt ]; then
      pip install --user -r requirements.txt
    else
      exit 0
    fi
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: airflow
    chart: airflow-3.0.5
    heritage: Tiller
    release: airflow
  name: airflow-scripts
  selfLink: /api/v1/namespaces/airflow/configmaps/airflow-scripts
