apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: airflow
    chart: airflow-3.0.5
    component: flower
    heritage: Tiller
    release: airflow
  name: airflow-flower
  selfLink: /apis/extensions/v1beta1/namespaces/airflow/deployments/airflow-flower
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airflow
      component: flower
      release: airflow
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config-env: d5a24d137bf90baf3fd2ed752845fef0e5647710e1260a803c9accc936929dcd
      creationTimestamp: null
      labels:
        app: airflow
        component: flower
        release: airflow
    spec:
      containers:
      - args:
        - flower
        env:
        - name: POSTGRES_USER
          value: postgres
        envFrom:
        - configMapRef:
            name: airflow-env
        image: puckel/docker-airflow:1.10.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: //
            port: flower
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: airflow-flower
        ports:
        - containerPort: 5555
          name: flower
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
