apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: postgresql
    chart: postgresql-0.13.1
    heritage: Tiller
    release: airflow
  name: airflow-postgresql
  selfLink: /api/v1/namespaces/airflow/persistentvolumeclaims/airflow-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-ef978821-ac70-11e9-b4d2-42010a800034
status: {}
