apiVersion: v1
data:
  postgres-password: YWlyZmxvdw==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: postgresql
    chart: postgresql-0.13.1
    heritage: Tiller
    release: airflow
  name: airflow-postgresql
  selfLink: /api/v1/namespaces/airflow/secrets/airflow-postgresql
type: Opaque
