apiVersion: v1
data:
  redis-password: YWlyZmxvdw==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: redis
    chart: redis-7.0.0
    heritage: Tiller
    release: airflow
  name: airflow-redis
  selfLink: /api/v1/namespaces/airflow/secrets/airflow-redis
type: Opaque
