apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: airflow
    chart: airflow-3.0.5
    component: web
    heritage: Tiller
    release: airflow
  name: airflow-web
  selfLink: /api/v1/namespaces/airflow/services/airflow-web
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: airflow
    component: web
    release: airflow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
