apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
    chart: redis-7.0.0
    heritage: Tiller
    release: airflow
  name: airflow-redis-headless
  selfLink: /api/v1/namespaces/airflow/services/airflow-redis-headless
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: airflow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
