apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: airflow
    chart: airflow-3.0.5
    component: worker
    heritage: Tiller
    release: airflow
  name: airflow-worker
  selfLink: /api/v1/namespaces/airflow/services/airflow-worker
spec:
  clusterIP: None
  ports:
  - name: worker
    port: 8793
    protocol: TCP
    targetPort: 8793
  selector:
    app: airflow
    component: worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
