apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: airflow
    chart: airflow-3.0.5
    component: flower
    heritage: Tiller
    release: airflow
  name: airflow-flower
  selfLink: /api/v1/namespaces/airflow/services/airflow-flower
spec:
  ports:
  - name: flower
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: airflow
    component: flower
    release: airflow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
